#!/bin/sh

# Start polybar
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done
polybar main &

feh --no-fehbg --bg-fill --randomize Pictures/* &
xset r rate 180 25 & # key repeat rate
xset m 3 4 & # mouse speed
setxkbmap it
sxhkd &
# Auto screenlock
csxlock -u "Welcome, pellettiero!" -b "#000000" -o "#FFFFFF"

