#!/bin/sh
# pellettiero's dotfiles - .xinitrc


# Merge .Xresources
xrdb -load "$XDG_CONFIG_HOME/xorg/xresources" &

xset -dpms &
xset s off &  # screen blanking off
xset -b & # audible bell off
xset r rate 150 50 & # key repeat rate
xset m 3 4 & # mouse speed
setxkbmap it

# Compositing manager
compton -b --config ~/.config/compton/compton.conf &

# Start redshift
redshift &

# NumLock on
numlockx on &
unclutter -root &
xsetroot -cursor_name left_ptr &
wmname LG3D

exec i3
